#!/bin/bash
# 🎨 GPT-ART Quick Commands
# Commandes rapides pour créer des œuvres

echo "🎨 GPT-ART Workflow Automator - Quick Reference"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📝 SYNTAXE DE BASE:"
echo "  python create_artwork.py -m <model> -r <run> -a <artworks...>"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🤖 MODÈLES DISPONIBLES:"
echo "  claude  - Claude (Anthropic)"
echo "  gpt     - GPT (OpenAI)"
echo "  gemini  - Gemini (Google)"
echo "  other   - Autre modèle"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "💡 EXEMPLES RAPIDES:"
echo ""
echo "  # Une seule œuvre"
echo "  python create_artwork.py -m claude -r my-run -a \"my-artwork\""
echo ""
echo "  # Plusieurs œuvres"
echo "  python create_artwork.py -m claude -r dark-poems -a \"void\" \"decay\" \"silence\""
echo ""
echo "  # Preview (dry-run)"
echo "  python create_artwork.py -m gpt -r test -a \"piece1\" --dry-run"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📋 WORKFLOW:"
echo "  1. Lancer le script → Crée la structure"
echo "  2. Remplir source.void → Code VOID"
echo "  3. Remplir compiled.txt → Art ASCII/glitch"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📖 DOCUMENTATION COMPLÈTE:"
echo "  - README.md           → Vue d'ensemble"
echo "  - WORKFLOW_GUIDE.md   → Guide détaillé du script"
echo "  - AGENTS.md           → Instructions pour l'IA"
echo ""
echo "═══════════════════════════════════════════════════════════"
